# -*- coding: utf-8 -*-
"""Students_Performance

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c7uOuYLNU3UwabOU9_bF55VZH-y5DxvK

Importing libraries like NumPy, Pandas, Matplotlib, and Seaborn.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

"""Reading data set in csv file called StudentsPerformance."""

df = pd.read_csv(r'/content/StudentsPerformance.csv')

"""To check how data set looks like using df.head() ."""

df.head()

"""Descriptive statistic parameters for the dataset."""

df.describe(include='all')

"""Check for missing values in our dataset."""

df.isnull().sum()

"""Graphical representation by using bar graph."""

plt.subplot(221)
df['gender'].value_counts().plot(kind='bar', title='Gender of students', figsize=(16,9))
plt.xticks(rotation=0)
plt.subplot(222)
df['race/ethnicity'].value_counts().plot(kind='bar', title='Race/ethnicity of students')
plt.xticks(rotation=0)
plt.subplot(223)
df['lunch'].value_counts().plot(kind='bar', title='Lunch status of students')

plt.xticks(rotation=0)

plt.subplot(224)
df['test preparation course'].value_counts().plot(kind='bar', title='Test preparation course')

plt.xticks(rotation=0)

plt.show()

"""Boxplot bold text of the numerical columns (math score, reading score, and writing score)"""

df.boxplot()

""" Distribution plot of the math score of the students"""

sns.distplot(df['math score'])

"""The correlation between the 3 scores with the help of a heatmap."""

corr = df.corr()
sns.heatmap(corr, annot=True, square=True)
plt.yticks(rotation=0)
plt.show()

sns.relplot(x='math score', y='writing score', hue='gender', data=df)

"""A relational plot in Seaborn,The relationship between 2 variables on different subsets of the dataset"""

df.groupby('parental level of education')[['math score', 'reading score', 'writing score']].mean().T.plot(figsize=(12,8))

"""Students’ performance in math, reading, and writing based on the level of education of their parents and test preparation course. we will make line plot to understend this."""

df.groupby('test preparation course')[['math score', 'reading score', 'writing score']].mean().T.plot(kind='barh', figsize=(10,10))

